# Use Unicode Strings
# http://wiki.rubyonrails.com/rails/pages/HowToUseUnicodeStrings
# MySQL 4.1 windows + Cygwin Ruby
login: &login
  adapter: mysql
  encoding: utf8
  username: root
  password: 
  host: LOCALHOST

development:
  database: grean_development
  <<: *login

test:
  database: grean_test
  <<: *login

production:
  database: grean_production
  <<: *login

# PostgreSQL 8.1 windows + Cygwin Ruby
#login: &login
#  adapter: postgresql
#  encoding: unicode
#  username: postgres
#  password: 
#  host: localhost
